### ISSUE TITLE
Please commit latest changes

### ISSUE THREAD

**Issue by LemADEC** [Ne0nx3r0/Quantum-Connectors#5]
Plugin was updated for Spigot 1.8, can you please commit the related sources?

**Comment by Ne0nx3r0** [comment]
Here you go:
https://github.com/Ne0nx3r0/Quantum-Connectors/commit/5032d3d93b2004ffcbf14b1b7533237f3658d6d5

The compiled jar is at:
http://dev.bukkit.org/bukkit-plugins/quantum-connectors/files/39-quantum-connectors-v2-5-6/

**Comment by LemADEC** [comment]
Apparently it's still compilated against Java 1.8:
```
[00:03:55 ERROR]: Could not load 'plugins/QuantumConnectors-2.5.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/ne0nx3r0/quantum/QuantumConnectors : Unsupported major.minor version 52.0
>       at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedClassVersionError: com/ne0nx3r0/quantum/QuantumConnectors : Unsupported major.minor version 52.0
>       at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
>       at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
>       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
>       at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
>       at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
>       at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
>       at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
>       at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
>       at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
>       at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
>       at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
>       at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-952179b-7bdb8f9]
>       ... 6 more
```

**Comment by Ne0nx3r0** [comment]
Odd, I thought I swapped the project to 1.6. The source is there anyway.

I'm unconvinced anyone should be running a Java release that is two years and two major versions behind the current one, but here's a new upload:
http://dev.bukkit.org/bukkit-plugins/quantum-connectors/files/41-quantum-connectors-v2-5-6/

**Comment by LemADEC** [comment]
Java 1.7 is still the standard for most Linux boxes out there.
Java 1.8 won't work with many mods, including Forge itself until quite recently. It'll take some time to convert.
